services:
    web:
      container_name: nginx
      build:
        context: ./client
        dockerfile: Dockerfile
      volumes:
        - ./nginx/:/etc/nginx/conf.d
      ports:
        - "80:80"
      depends_on:
        - api
      networks:
        - dts-test
  
    api:
      container_name: api
      build:
        context: ./server
        dockerfile: Dockerfile
      environment:
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_DB=${DB_NAME}
        - POSTGRES_HOST=${DB_HOST}
        - POSTGRES_PORT=${DB_PORT}
      ports:
        - "8080:8080"
      depends_on:
        db_test:
          condition: service_healthy
      networks:
        - dts-test
  
    db_test:
      image: postgres:16.4
      container_name: ${DB_HOST}
      environment:
        - PGUSER=${DB_USER}
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_DB=${DB_NAME}
        - POSTGRES_HOST=${DB_HOST}
      ports:
        - '4568:${DB_PORT}'
      networks:
        - dts-test
      healthcheck:
        test: "pg_isready -h db_test"
        interval: 5s
        timeout: 5s
        retries: 5

networks:
  dts-test:
    driver: bridge